Add logic to set the operator's status in the NFD CR
kubernetes-sigs/node-feature-discovery-operator pull request #84
Opened 2021-08-26 19:14 UTC by courtneypacheco

Add logic that sets the operator's status in the NFD CR based on whether one or more of NFD's resources is: degraded, progressing, upgradeable, or available. Also add a "applyComponents" function to simplify readability.

2021-08-30 12:43 UTC, courtneypacheco commented
@marquiz Thanks! I noticed some of my tests failed, so I'm adding fixes. I will certainly rebase. :)

2021-08-30 17:13 UTC, courtneypacheco commented
@marquiz Just squashed commits and rebased. PTAL.

2021-09-28 15:52 UTC, ArangoGutierrez commented
> @marquiz Just squashed commits and rebased. PTAL.

@marquiz lgtm?

2021-09-28 15:52 UTC, ArangoGutierrez approved these changes
This works downstream
waiting on @marquiz for lgtm

2021-09-29 07:30 UTC, marquiz requested changes
Thanks for the PR!

I gave it a quick look, not ready for merging, yet 😉  I'm most concerned about the dependency to openshift. I know we already have some but we should keep it at a very minimum (and possibly eliminate some of the existing, too)

2021-09-29 07:30 UTC, marquiz commented on controllers/nodefeaturediscovery_status.go
> +	conditionsv1 "github.com/openshift/custom-resource-status/conditions/v1"
Hmm, I'm not sure we want to depend on downstream (openshift) at least this heavily 🧐   I think we should use k8s metav1 (`k8s.io/apimachinery/pkg/apis/meta/v1`).

Maybe `ConditionType`s is something that we could use from openshift 🤔  Or then just copy paste those here in order to break the dependency

2021-09-30 16:04 UTC, ArangoGutierrez commented
Superseed by https://github.com/kubernetes-sigs/node-feature-discovery-operator/pull/88
/close

2021-09-30 16:04 UTC, closed without merging