Migrate loggin to klogv2
kubernetes-sigs/node-feature-discovery-operator pull request #93
Opened 2021-10-04 19:44 UTC by ArangoGutierrez

2021-10-04 20:38 UTC, marquiz reviewed
Thanks, looks good, now 👍 Just some nitting on the consistency of log messages, sorry 🙄  Will take a fresh look tomorrow with fresh eyes

2021-10-04 20:38 UTC, marquiz commented on controllers/nodefeaturediscovery_controls.go
> +		klog.Info("ServiceAccount %q, Not found, creating", obj.Name)
```suggestion
		klog.Info("ServiceAccount %q not found, creating", obj.Name)
```

2021-10-04 20:38 UTC, marquiz commented on controllers/nodefeaturediscovery_controls.go
> +		klog.Info("ClusterRole %q, Not found, creating", obj.Name)
```suggestion
		klog.Info("ClusterRole %q not found, creating", obj.Name)
```

2021-10-04 20:38 UTC, marquiz commented on controllers/nodefeaturediscovery_controls.go
> +	klog.Info("ClusterRole Found, updating", obj.Name)
```suggestion
	klog.Info("ClusterRole found, updating", obj.Name)
```

2021-10-04 20:38 UTC, marquiz commented on controllers/nodefeaturediscovery_controls.go
> +	klog.Info("ClusterRoleBinding %q Found on Namespace %q, updating", obj.Name, obj.Namespace)
```suggestion
	klog.Info("ClusterRoleBinding %q found in Namespace %q, updating", obj.Name, obj.Namespace)
```

2021-10-04 20:38 UTC, marquiz commented on controllers/nodefeaturediscovery_controls.go
> +		klog.Info("ClusterRoleBinding %q Not found on Namespace %q, creating", obj.Name, obj.Namespace)
```suggestion
		klog.Info("ClusterRoleBinding %q not found in Namespace %q, creating", obj.Name, obj.Namespace)
```

2021-10-04 20:38 UTC, marquiz commented on controllers/nodefeaturediscovery_controls.go
> +		klog.Info("Role %q, Not found on Namespace %q, creating", obj.Name, obj.Namespace)
```suggestion
		klog.Info("Role %q not found in Namespace %q, creating", obj.Name, obj.Namespace)
```

2021-10-04 20:38 UTC, marquiz commented on controllers/nodefeaturediscovery_controls.go
> +		klog.Info("RoleBinding %q, Not found on Namespace %q, creating", obj.Name, obj.Namespace)
```suggestion
		klog.Info("RoleBinding %q not found in Namespace %q, creating", obj.Name, obj.Namespace)
```

2021-10-04 20:38 UTC, marquiz commented on controllers/nodefeaturediscovery_controls.go
> +	klog.Info("RoleBinding %q Found on Namespace %q, updating", obj.Name, obj.Namespace)
```suggestion
	klog.Info("RoleBinding %q found in Namespace %q, updating", obj.Name, obj.Namespace)
```

2021-10-04 20:38 UTC, marquiz commented on controllers/nodefeaturediscovery_controls.go
> +		klog.Info("ConfigMap %q Not found on Namespace %q, creating", obj.Name, obj.Namespace)
```suggestion
		klog.Info("ConfigMap %q not found in Namespace %q, creating", obj.Name, obj.Namespace)
```

2021-10-04 20:38 UTC, marquiz commented on controllers/nodefeaturediscovery_controls.go
> +	klog.Info("looking for Daemonset %q on Namespace %q", obj.Name, obj.Namespace)
```suggestion
	klog.Info("Looking for Daemonset %q in Namespace %q", obj.Name, obj.Namespace)
```

2021-10-04 20:38 UTC, marquiz commented on controllers/nodefeaturediscovery_controls.go
> +		klog.Info("Daemonset %q on Namespace %q Not found, creating", obj.Name, obj.Namespace)
```suggestion
		klog.Info("Daemonset %q in Namespace %q not found, creating", obj.Name, obj.Namespace)
```

2021-10-04 20:38 UTC, marquiz commented on controllers/nodefeaturediscovery_controls.go
> +	klog.Info("Daemonset %q on Namespace %q Found, updating", obj.Name, obj.Namespace)
```suggestion
	klog.Info("Daemonset %q in Namespace %q found, updating", obj.Name, obj.Namespace)
```

2021-10-04 20:38 UTC, marquiz commented on controllers/nodefeaturediscovery_controls.go
> +	klog.Info("looking for Service %q in Namespace %q", obj.Name, obj.Namespace)
```suggestion
	klog.Info("Looking for Service %q in Namespace %q", obj.Name, obj.Namespace)
```

2021-10-04 20:38 UTC, marquiz commented on controllers/nodefeaturediscovery_controls.go
> +		klog.Info("Service %q in Namespace %q, Not found, creating", obj.Name, obj.Namespace)
```suggestion
		klog.Info("Service %q in Namespace %q not found, creating", obj.Name, obj.Namespace)
```

2021-10-04 20:38 UTC, marquiz commented on controllers/nodefeaturediscovery_controls.go
> +	klog.Info("Looking for ClusterRoleBinding %q on Namespace %q", obj.Name, obj.Namespace)
supert nit: in/on namespace, use consistently 😄 

```suggestion
	klog.Info("Looking for ClusterRoleBinding %q in Namespace %q", obj.Name, obj.Namespace)
```

2021-10-04 20:38 UTC, marquiz commented on controllers/nodefeaturediscovery_controls.go
> +			klog.Info("Couldn't create ClusterRoleBinding %q on Namespace %q", obj.Name, obj.Namespace)
```suggestion
			klog.Info("Couldn't create ClusterRoleBinding %q in Namespace %q", obj.Name, obj.Namespace)
```

2021-10-04 20:38 UTC, marquiz commented on controllers/nodefeaturediscovery_controls.go
> +	klog.Info("Looking for Role %q on Namespace %q", obj.Name, obj.Namespace)
```suggestion
	klog.Info("Looking for Role %q in Namespace %q", obj.Name, obj.Namespace)
```

2021-10-04 20:38 UTC, marquiz commented on controllers/nodefeaturediscovery_controls.go
> +			klog.Info("Couldn't create Role %q on Namespace %q", obj.Name, obj.Namespace)
```suggestion
			klog.Info("Couldn't create Role %q in Namespace %q", obj.Name, obj.Namespace)
```

2021-10-04 20:38 UTC, marquiz commented on controllers/nodefeaturediscovery_controls.go
> +	klog.Info("Found Role %q on Namespace %q, updating", obj.Name, obj.Namespace)
```suggestion
	klog.Info("Found Role %q in Namespace %q, updating", obj.Name, obj.Namespace)
```

2021-10-04 20:38 UTC, marquiz commented on controllers/nodefeaturediscovery_controls.go
> +	klog.Info("Looking for RoleBinding %q on Namespace %q", obj.Name, obj.Namespace)
```suggestion
	klog.Info("Looking for RoleBinding %q in Namespace %q", obj.Name, obj.Namespace)
```

2021-10-04 20:38 UTC, marquiz commented on controllers/nodefeaturediscovery_controls.go
> +			klog.Info("Couldn't create RoleBinding %q on namespace %q", obj.Name, obj.Namespace)
```suggestion
			klog.Info("Couldn't create RoleBinding %q in namespace %q", obj.Name, obj.Namespace)
```

2021-10-04 20:38 UTC, marquiz commented on controllers/nodefeaturediscovery_controls.go
> +	klog.Info("Looking for ConfigMap %q on Namespace %q", obj.Name, obj.Namespace)
```suggestion
	klog.Info("Looking for ConfigMap %q in Namespace %q", obj.Name, obj.Namespace)
```

2021-10-04 20:38 UTC, marquiz commented on controllers/nodefeaturediscovery_controls.go
> +			klog.Info("Couldn't create ConfigMap %q on Namespace %q", obj.Name, obj.Namespace)
```suggestion
			klog.Info("Couldn't create ConfigMap %q in Namespace %q", obj.Name, obj.Namespace)
```

2021-10-04 20:38 UTC, marquiz commented on controllers/nodefeaturediscovery_controls.go
> +	klog.Info("Found ConfigMap %q on Namespace %q, updating", obj.Name, obj.Namespace)
```suggestion
	klog.Info("Found ConfigMap %q in Namespace %q, updating", obj.Name, obj.Namespace)
```

2021-10-04 20:38 UTC, marquiz commented on controllers/nodefeaturediscovery_controls.go
> +			klog.Info("Couldn't create Daemonset %q on Namespace %q", obj.Name, obj.Namespace)
```suggestion
			klog.Info("Couldn't create Daemonset %q in Namespace %q", obj.Name, obj.Namespace)
```

2021-10-04 20:38 UTC, marquiz commented on controllers/nodefeaturediscovery_controls.go
> +	klog.Info("Looking for ServiceAccount %q on Namespace %q", obj.Name, obj.Namespace)
supert nit: in/on namespace, use consistently 😄 

```suggestion
	klog.Info("Looking for ServiceAccount %q in Namespace %q", obj.Name, obj.Namespace)
```

2021-10-04 20:38 UTC, marquiz commented on controllers/nodefeaturediscovery_controls.go
> +	klog.Info("Found ServiceAccount %q on Namespace %q, skipping update", obj.Name, obj.Namespace)
```suggestion
	klog.Info("Found ServiceAccount %q in Namespace %q, skipping update", obj.Name, obj.Namespace)
```

2021-10-04 20:38 UTC, marquiz commented on controllers/nodefeaturediscovery_controls.go
> +	klog.Info("Looking for ClusterRole %q on Namespace %", obj.Name, obj.Namespace)
```suggestion
	klog.Info("Looking for ClusterRole %q in Namespace %", obj.Name, obj.Namespace)
```

2021-10-05 06:17 UTC, marquiz requested changes
Could you squash the two latter commits into one. And, start the commit message (of the second commit) with a capital letter 😉 

Otherwise lgtm 👍

2021-10-05 13:59 UTC, ArangoGutierrez commented
> Could you squash the two latter commits into one. And, start the commit message (of the second commit) with a capital letter wink
> 
> Otherwise lgtm +1

Done

2021-10-05 16:35 UTC, ArangoGutierrez commented
/assign @marquiz

2021-10-05 17:24 UTC, marquiz approved these changes
Looks ready to rock mainline 🎸 
/lgtm

2021-10-05 17:25 UTC, merged